# Generated by Django 4.0.5 on 2022-06-30 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('link', models.URLField()),
                ('description', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('publish_date', models.DateTimeField()),
            ],
            options={
                'verbose_name_plural': 'News',
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Rss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('press_name', models.CharField(max_length=200)),
                ('link', models.URLField()),
            ],
            options={
                'verbose_name': 'RSS',
                'verbose_name_plural': 'RSSs',
            },
        ),
    ]
